# Configuration for markdownlint-cli linter

# MD012/no-multiple-blanks - Multiple consecutive blank lines
MD012: false
# MD013/line-length - Line length
MD013: false
# MD033/no-inline-html - Inline HTML
MD033:
  # Allowed elements
  allowed_elements: [ BR ]

